### ISSUE TITLE
OSError:checkpoint

### ISSUE THREAD

**Issue by LinhanZ** [amazon-research/BartGraphSumm#2]
Hello,
When I run with the code for Bart Baseline, there is an error saying that:

OSError: Model file not found: /home/.../results/bart-large-multinews-model1/checkpoint_best.pt

Could you give me some advice? Is this checkpoint are produced by train.py? or need to be download before I run this code?

**Comment by lgplgplgplgp** [comment]
Hello. Do you have the data for this model? Could you please provide it? Thank you.
